header:
  version: 8

local_conf_header:
  standard: |
    CONF_VERSION = "2"
    PACKAGE_CLASSES = "package_rpm"
    SDKMACHINE = "x86_64"
    USER_CLASSES = "buildstats"
    PATCHRESOLVE = "noop"
    TOOLCHAIN ?= "clang"

    # Top level download and sstate cache directories
    DL_DIR = "${TOPDIR}/../downloads"
    SSTATE_DIR = "${TOPDIR}/../sstate-cache"
  debug-tweaks: |
    IMAGE_FEATURES += "empty-root-password allow-empty-password allow-root-login post-install-logging"
    IMAGE_INSTALL:append = " strace grpc protobuf protobuf-c"
  diskmon: |
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
  license: |
    # Uncomment next line to allow the license
    # See: linux-firmware-rpidistro in docs/ipcompliance.md
    LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"
    LICENSE_FLAGS_ACCEPTED += "commercial_ffmpeg commercial_rpidistro-ffmpeg"
    # Accept all commercial licenses including x264
    LICENSE_FLAGS_ACCEPTED += "commercial commercial_x264"
    # Prefer rpidistro-ffmpeg
    PREFERRED_PROVIDER_ffmpeg += "rpidistro-ffmpeg"
